name: Docker Build and Push

on:
  push:
    branches:
      - main  # This workflow will trigger on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-22.04  # Use a fixed Ubuntu version to avoid future issues

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log into Docker Hub
      run: |
        echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t my-app .

    - name: Push Docker image
      run: |
        docker push my-app:latest
