name: Java CI with Maven, Docker, and Kubernetes Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Continuous Integration (CI)
  ci:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Specify Java version 17
          distribution: 'zulu'  # Use Zulu OpenJDK distribution
          cache: 'maven'  # Enable caching for Maven dependencies

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install

      # Build Docker image
      - name: Build Docker image
        run: docker build -t mynewapp .

  # Continuous Deployment (CD)
  cd:
    runs-on: ubuntu-latest
    needs: ci  # CD job runs after CI job
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Kubernetes configuration (if required)
      - name: Set up Kubernetes configuration
        run: |
          echo "$KUBECONFIG" > $HOME/.kube/config
          mkdir -p $HOME/.kube && chmod 600 $HOME/.kube/config

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
