name: Java CI/CD with Maven, Docker, and AWS EKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Java JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'

    # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Build the project with Maven
    - name: Build with Maven
      run: mvn clean install

    # Build Docker image for the app
    - name: Build Docker image
      run: docker build -t mynewapp .

    # AWS Configuration
    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-west-2  # Use your AWS region

    # Push the Docker image to AWS ECR
    - name: Push Docker image to AWS ECR
      run: |
        $(aws ecr get-login --no-include-email --region us-west-2)
        docker tag mynewapp:latest 879381276096.dkr.ecr.us-west-2.amazonaws.com/mynewapp:latest
        docker push 879381276096.dkr.ecr.us-west-2.amazonaws.com/mynewapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    # Checkout the repository code again
    - name: Checkout code
      uses: actions/checkout@v2

    # AWS Configuration
    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-west-2  # Use your AWS region

    # Deploy the app to AWS EKS
    - name: Deploy to AWS EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl rollout status deployment/mynewapp-deployment
