name: Java CI/CD with Maven, Docker, and AWS ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Specify Java version 17
          distribution: 'zulu'  # Use Zulu OpenJDK distribution
          cache: 'maven'  # Enable caching for Maven dependencies

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install

      # Build Docker image
      - name: Build Docker image
        run: docker build -t mynewapp .

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job runs after the 'build' job

    steps:
      # Checkout code again in deploy job
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS CLI with credentials from GitHub Secrets
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Use your AWS region

      # Login to AWS ECR
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 879381276096.dkr.ecr.us-west-2.amazonaws.com

      # Tag Docker image for AWS ECR
      - name: Tag Docker image for ECR
        run: |
          docker tag mynewapp:latest 879381276096.dkr.ecr.us-west-2.amazonaws.com/mynewapp:latest

      # Push Docker image to AWS ECR
      - name: Push Docker image to AWS ECR
        run: |
          docker push 879381276096.dkr.ecr.us-west-2.amazonaws.com/mynewapp:latest
